name: test
on: push
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6","3.7","3.8","3.9","3.10","3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: All test
        run: bash -xv ./test.bash
  windws-latest:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.6","3.7","3.8","3.9","3.10","3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: All test
        run: bash -xv ./test.bash
  macos-latest:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.6","3.7","3.8","3.9","3.10","3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: All test
        run: bash -xv ./test.bash
